---
abstract: 'The great new App::multiwhich!'
author:
  - 'A. Sinan Unur <nanis@cpan.org>'
build_requires:
  Test::Exception: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142060'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-multiwhich
no_index:
  directory:
    - t
    - inc
requires:
  File::Basename: '0'
  File::Spec::Functions: '3.47'
  Perl::OSType: '1.006'
  YAML::XS: '0.48'
  namespace::sweep: '0.006'
  perl: '5.006'
resources:
  repository: git://github.com/nanis/App-multiwhich.git
version: '0.001'
